### ISSUE TITLE
Url parameters with slashes issue

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#112]
ui-router causing problem where state parameters containing slashes are not properly encode/decoded.

Example: CAL_ALF_14/07/2014 14:54:56 slashes are double encoded to CAL_ALF_14%252F07%252F2014%2014%3A54%3A56.

Bug was already reported:

https://github.com/angular-ui/ui-router/issues/1973
https://github.com/angular-ui/ui-router/pull/2071

**Comment by jodysalt** [comment]
This is no longer an issue (i.e. I can't replicate it).
