### ISSUE TITLE
Add ability to combine values from fields in a column

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#126]
Add ability to merge values from diffrent fields to a single column. e.g.

Column with the combined values `<name>-<visitId>`

Note: This will be for display only, it will not be possible to sort, filter by the combined string since sorting and ordering are performed on the icat server. Sort and order will still be done using the configured field property.

**Comment by RKrahl** [comment]
For sorting, you could use `ORDER BY i.name, i.visitId`, e.g. combine all fields in the same order that is used to combine the value.

**Comment by jodysalt** [comment]
I've had some thoughts about this. In that I can't really see how this feature will add any value to a* scientist's work flow. I think less is more here, as each entity attribute is better off in a separate column, as it is so much more clear and obvious what it represents.

**Comment by RKrahl** [comment]
Let me explain why this would be helpful to us at HZB:

A crucial point in our data management work flow is that the user must register the proper proposal id with the experiment control software when starting a measurement at the instrument.  This is the only way to attribute the data from the measurement to the right investigation.  If the user gets this wrong, the data will end up somewhere, but not at the right place in the data repository.  There is not too much that we can do to guarantee that this is done correctly other then advising the user of the importance of this step and making it as easy as possible for the user.

A typical proposal id at HZB looks like "15202293-ST-2.1-P".  (This would be the first of two technical parts from standard type proposal from the second semester 2015 at BESSY II.)  To understand all this, you need to know that a proposal consists of the main part that describes the scientific case and then of one or more technical parts, each describing the method that the proposer wants to use (e.g. if the proposer wants to examine the same sample with two different instruments, the proposal might have two technical parts).  In this case, the "15202293-ST" is the id of the main part and the "2.1-P" is the id of one of the technical parts.  In the ICAT, I store the "15202293-ST" part in Investigation.name and the "2.1-P" part in Investigation.visitId.

But the average user is not supposed to understand all the gory details of how our proposal ids are composed and what each of the components is supposed to denote.  Very certainly, the user also does not care.  All the user needs to know, is: "'15202293-ST-2.1-P' is your proposal id for this beam time and please enter it like this when starting the measurement."  That is, I want to communicate the complete proposal id as an opaque string to the user whenever possible.  That is why I want a simple column "Proposal id" in TopCAT.

**Comment by jodysalt** [comment]
Hi Rolf,

Makes perfect sense! As long as features have a good solid reason behind it, I'm very much behind it. I just don't want code written that doesn't get used.

Jody
