### ISSUE TITLE
Strange behavior in Browse tab for an investigation with many instruments

### ISSUE THREAD

**Issue by RKrahl** [icatproject/topcat#130]
The Browse tab in TopCAT v2 shows strange behavior in the case of an investigation with many instruments.

How to reproduce:

1. Have an Investigation with three InvestigationInstrument relations in the ICAT.
2. Make sure you have an instrument column in the Investigation Browse tab in TopCAT.  (As the Beamline column in the default configuration.)
3. Select the Investigation in the Browse tab.
4. Select the investigation with the many instruments by entering its name.  (Probably not needed, but makes it easier to observe the issue.)  The tab shows only one row with the selected investigation.
5. Click on "Sort Ascending" in the Instrument column.  The tab now show three identical rows, each displaying the same investigation with the same instrument.
6. Click on "Remove Sort" in the Instrument column.  The tab gets back to only one row with the investigation.

**Comment by RKrahl** [comment]
This is the query that TopCAT sends after clicking on "Sort Ascending":
```sql
SELECT inv FROM Investigation inv, inv.facility f, inv.investigationInstruments invinvestigationInstruments WHERE (f.id = 155) AND (UPPER(inv.name) LIKE '%88888888-XX%') ORDER BY invinvestigationInstruments.instrument.fullName ASC INCLUDE inv.investigationInstruments.instrument LIMIT 0, 50
```

If you try this query in an ICAT client, you get a list with three items, each of them the same investigation object in the reply.  This is also the reply that TopCAT gets.

**Comment by wayne-chung** [comment]
I think because there are 3 instruments for the investigation, the same investigation object is returned 3 times for for the query. Adding DISTINCT to the query should fix the issue.

**Comment by RKrahl** [comment]
No.  I already tried that.  Adding DISTINCT to the query does not change the result:

```python
>>> query = "SELECT inv FROM Investigation inv, inv.facility f, inv.investigationInstruments invinvestigationInstruments WHERE (f.id = 155) AND (UPPER(inv.name) LIKE '%88888888-XX%') ORDER BY invinvestigationInstruments.instrument.fullName ASC INCLUDE inv.investigationInstruments.instrument LIMIT 0, 50"
>>> result = client.search(query)
>>> len(result)
3
>>> result[0] == result[1]
True
>>> result[1] == result[2]
True
>>> 
>>> query2 = "SELECT DISTINCT inv FROM Investigation inv, inv.facility f, inv.investigationInstruments invinvestigationInstruments WHERE (f.id = 155) AND (UPPER(inv.name) LIKE '%88888888-XX%') ORDER BY invinvestigationInstruments.instrument.fullName ASC INCLUDE inv.investigationInstruments.instrument LIMIT 0, 50"
>>> result2 = client.search(query)
>>> result2 == result
True
```

**Comment by wayne-chung** [comment]
The ORDER BY cause in the icat query causes the duplication which I've no idea how to resolve by query alone. 

To get around the issue, I've uniqued the returned result by entitiy id. 

```
        function uniqueEntityById(data) {
            return _.uniq(data, function(item) {
                return item.id;
            });
        }
```
The total count query was returning the correct result and should now match the number of unique results.

The only issue with this solution is that a page of say 50 result may by less due to the removel of duplicates.

**Comment by tomgriffinstfc** [comment]
Issue opened in icat.server
https://github.com/icatproject/icat.server/issues/154

**Comment by RKrahl** [comment]
There is more quirks related to the fact that we have multiple values for a single column:

For testing, I created two investigations, "15000002-XX" with a single instrument "E2 - Flat-Cone Diffractometer" and "15000003-XX" with two instruments, "PM3 - PM3 Dipole PGM variable polarisation" and "ALICE".  If I select these two by name and sort ascending by instrument, I get:

Name        | Instrument
----------- | ---------------
15000003-XX | PM3 - PM3 Di...
15000002-XX | E2 - Flat-Co...
15000003-XX | PM3 - PM3 Di...

So even after eliminating the duplicates, the ordering as displayed in the column might not be consistent.

If I select "ALICE" in the instrument column, I get:

Name        | Instrument
----------- | ---------------
15000003-XX | PM3 - PM3 Di...

In a sense, this is correct, because this is the investigation related to ALICE.  Nevertheless its confusing to get results that display an instrument name that does not match the instrument you were searching for.

I admit that I have no idea how to solve this or whether there is any consistent solution to this.

**Comment by wayne-chung** [comment]
Propose as per screenshot.

If field has more than one value, a list icon is show beside the displayed value. On hover over the list icon, it will display all the possible values in a tooltip.

![multiple_values](https://cloud.githubusercontent.com/assets/12646305/10765419/8b46001e-7cca-11e5-94b5-dd5d8b69d914.png)

**Comment by RKrahl** [comment]
Looks good!

**Comment by fisherab** [comment]
You have a mistake in evaluation of result2 it should use query2 rather
than query!
Steve

**Comment by RKrahl** [comment]
Am Mittwoch, 28. Oktober 2015, 09:52:19 schrieb Steve Fisher:
> You have a mistake in evaluation of result2 it should use query2 rather
> than query!

You're right.  Error on Cut'n'Paste into the discussion.

But this doesn't change the outcome, the corrected test yields the
same output.

**Comment by fisherab** [comment]
I will investigate next week.
Steve
