### ISSUE TITLE
Download ready emails use the user's name, not fullname

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/topcat#132]
Download ready alert emails currently look use the user_.name attribute which is typically less friendly than user_.fullname.

e.g. "Hi xyz79436" rather than "Hi Tom Griffin"

Where a fullname is available this should be used in the email.

**Comment by wayne-chung** [comment]
In order to do this, I have to store the user's fullname is the database when download request is made. It is not possible to get the fullname just before an email is sent out as a query need to be made to icat and there may not be a valid session at that point in time.
