### ISSUE TITLE
IDS options should be administrator controlled (config file)

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/topcat#133]
Currently all download requests to IDS specify ZIP_AND_COMPRESS.

This should be a setting in the config file so the admin can control it.

**Comment by wayne-chung** [comment]
I've now added a setting to topcat.properties but thinking about it, this will apply globally to all IDSs. It would be better to have this setting in the frontend topcat.json where it can be specified individually for each facility.

Ideally the recommended setting should come from the IDS itself?

**Comment by wayne-chung** [comment]
This is now moved to topcat.json file as an optional property name zipType in the downloadTransportType object:

```
            "downloadTransportType": [
                {
                    "translateDisplayName" : "DOWNLOAD.TRANSPORT.HTTPS.NAME",
                    "type" : "https",
                    "default" : true,
                    "url": "https://myids.server.ac.uk",
                    "zipType": "ZIP"
                }
            ],
```
If not specified, it will default to ZIP (zip without compression). The other option is ZIP_AND_COMPRESS (zip with compression).

The property only affects https downloads.
