### ISSUE TITLE
Ability to cancel a download/restore

### ISSUE THREAD

**Issue by kevinphippsstfc** [icatproject/topcat#152]
If the user realises they have requested some data by mistake (particularly a large amount) then they should be able to cancel it in TopCAT. This probably requires improvements to the IDS, poll script etc so once a mechanism has been decided on, tickets on those components should be created.

**Comment by tomgriffinstfc** [comment]
https://github.com/icatproject/ids.server/issues/41

**Comment by fisherab** [comment]
I don't see that any change to the IDS is required. It could only be a
concern with two level storage. If a restore is requested that file may
have been requested by two people so I would not want to cancel the restore
request. TopCAT could send an archive request - but that is potentially
more disruptive.

Steve

**Comment by fisherab** [comment]
What is the status of this one please. It seems that TopCAT just has to forget about the prepareData request. There is nothing further to do in the IDS

**Comment by jodysalt** [comment]
The interface is there to allow you to pause and delete the download. This will do the equivalent of forgetting the preparedId.
