### ISSUE TITLE
It is possible to remove the last remaining column and there appears to be no way to get it back

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/topcat#155]
on topcat-dev, it is possible to remove the last remaining column and 
there appears to be no way to get it back...

It does come back if you go back to "top" and navigate back to 
"DIAMOND", luckily!

**Comment by jodysalt** [comment]
This is actually a "feature" of ui grid - shall I just disable it (as I don't think there is a very good use case for it) or should I create a "restore" button/feature.

**Comment by tomgriffinstfc** [comment]
I think a reset button would be better - more generally useful.
Greg?

**Comment by gwm** [comment]
can't see the point of being able to remove it in the first place but in the general case... I don't know. I was just bringing it to your attention!

**Comment by jodysalt** [comment]
I suggest then, we should disable this "feature". If people then specifically ask for this we'll have another think.

The only potentual use case I could think for this is someone wanted share a link (i.e. url) where the table has a reduced set of columns to highlight a particular point. In my limited experience I would guess this would be an edge case, and so we should only implement it if lots of people ask for it (i.e. the scientists). If we were to implement this feature it would just add clutter/confusion to the vast bulk of people who will never use it.

How would you like me to proceed on this?

**Comment by tomgriffinstfc** [comment]
Are you talking about taking away the ability to remove any column, or just the ability to remove the last column.
I think Alun has raised an issue before about restoring columns, which doesn't seem to be possible at the moment. If we can't get them back then we shouldn't be able to remove them.

**Comment by tomgriffinstfc** [comment]
Columns can now be resized by the user, so the remove feature can be disabled
