### ISSUE TITLE
Verify timeout behavior is clear

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/topcat#160]
TopCAT v1 has an issue where when a session times out, the user can recieve confusing and technical error messages.

Verify that ToPCATv2 handles timouts (the user going away overnight and leaving the browser open) more gracefully - i.e. by prompting the user to log in, then resuming

**Comment by jodysalt** [comment]
As long as your browser remains open Topcat v2 will keep the session open by refreshing it periodically.
