### ISSUE TITLE
Partial cart downloads

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/topcat#166]
Add tickboxes to the Cart page to allow partial cart downloads

**Comment by jodysalt** [comment]
Is this still require now the cart works a different way? What problem is it trying to solve?

**Comment by jodysalt** [comment]
Just had use case explained - you might want to skip downloading of large items. So ignore previous comment.

**Comment by tomgriffinstfc** [comment]
Duplicate of #145
