### ISSUE TITLE
Customise config for Diamond

### ISSUE THREAD

**Issue by jodysalt** [icatproject/topcat#185]
* Add visit id to search panel.
* remove visit ID from my data?
* Columns need to be resizable
* To go live "coming soon" in search tab.

**Comment by fisherab** [comment]
Please explain what this is - and why it contains anything Diamond specific?

**Comment by jodysalt** [comment]
I'm refering to the topcat_dls.json file. Which is just a topcat.json config file configured for Diamond. Basically on the next sprint review I want to make sure topcat-dev server gets configured as close to production as possible (which is what I'll use the topcat_dls.json file for). So don't worry; there is nothing Diamond specific.
