### ISSUE TITLE
Investigate Search by run number

### ISSUE THREAD

**Issue by Softey** [icatproject/topcat#196]

**Comment by jodysalt** [comment]
To quote feedback from Peter:

" Providing a tab to download by run number (with the usual access permission control). When I go to PSI for muon experiments they have a very simple web interface to download data (as ISIS used to have): http://musruser.psi.ch/cgi-bin/SearchDB.cgi. The old ISIS one may actually be a better model: http://data.isis.rl.ac.uk/. Oftentimes the users know very specifically which extra runs they want to download but are hazy on the metadata that goes with them and files them in TOPCAT. I’d say that perhaps a quarter of users know the RB number they’re working on off the top of their head when they’re on the beamline and maybe half have it somewhere about their person. Printing an instrument schedule with the RB numbers on is invaluable, but doesn’t help beyond the cabin."

"Also showing the RB numbers in My Data would be helpful. They are probably the clearest cataloguing tool we have and experiment titles often show little variety for a given user, some are better than others."

**Comment by jodysalt** [comment]
At the Investigation level we can get a run number range:

tc.icat('isis').query("select investigation from Investigation investigation, investigation.parameters as parameter, parameter.type as type where investigation.name = '10000' and type.name = 'run_number_range' include investigation.parameters").log()

**Comment by jodysalt** [comment]
At the datafile level we can search by run number:

tc.icat('isis').query("select datafile from Datafile datafile, datafile.parameters as parameter, parameter.type as type where type.name = 'run_number' and parameter.numericValue = 1207 include datafile.parameters").log()
