### ISSUE TITLE
IDS getIcatUrl inconsistant

### ISSUE THREAD

**Issue by jodysalt** [icatproject/topcat#233]
If you go to:

https://idsdev2.isis.cclrc.ac.uk/ids/getIcatUrl (1.6.0-SNAPSHOT)

you get:

https://icatdev15.isis.cclrc.ac.uk/ICATService/ICAT?wsdl

and if you got to:

https://fdsgos11.fds.rl.ac.uk/ids/getIcatUrl (1.5.0)

you get:

https://facilities02.esc.rl.ac.uk

(I'm guessing one is right and the other wrong)

**Comment by jodysalt** [comment]
Accidently place this under Topcat

**Comment by fisherab** [comment]
This is probably because of the way the ids has been configured on idsdev2. I will add some code to the ids to remove trailing stuff for WSDL - which is unfortunately different for wildfly and glassfish. I will add some messy code to address this.

**Comment by jodysalt** [comment]
Yes - it was misconfigured
