### ISSUE TITLE
Incorrect state listed in downloads window for Globus downloads

### ISSUE THREAD

**Issue by frazzleuk** [icatproject/topcat#242]
If you selected data that is 'Available' then proceed with a Globus download request, the downloads window lists the status of the download as 'Restoring from Tape'.

This should be set to something like 'Preparing'.

**Comment by jodysalt** [comment]
This also applies to scarf - and could make things very confusing to the end user.

**Comment by jodysalt** [comment]
This no longer is an issue because the state information has been removed from the Cart.
