### ISSUE TITLE
TopCAT displays a blank white page if the IDS is not running

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/topcat#271]
We had an issue with the ISIS IDS server.
When the IDS server was not running, TopCAT just displays a blank white page - no log on box etc.

It would be better to display a meaningful error message/holding page, or perhaps continue to allow the user to browse.

**Comment by jodysalt** [comment]
The way ISIS's Topcat is configured the icatUrl option is not specified, instead it performs a getIcatUrl call:

https://isisicatds.stfc.ac.uk/ids/getIcatUrl

However, you can explicitly specify the the icatUrl option which would then still let you browse.

Yes, I agree that there should be some sort of message for this situation.
