### ISSUE TITLE
Permanent spinner

### ISSUE THREAD

**Issue by fisherab** [icatproject/topcat#284]
When browsing a visit if there is no associated beam line I get a spinner that never stops spinning.

This relates to the latest published snapshot https://repo.icatproject.org/repo/org/icatproject/topcat/2.2.0-SNAPSHOT/topcat-2.2.0-20160922.145159-5-distro.zip

**Comment by fisherab** [comment]
I am delaying this to milestone 2.3 on the assumption that it's not a problem than will affect most serious sites

**Comment by jodysalt** [comment]
I have already fixed this. But accidently removed some of the logic that dealt with  this in #257. So I have reintroduced this.
