### ISSUE TITLE
TopCAT 2.3.0 error during installation with Glassfish 

### ISSUE THREAD

**Issue by antolinos** [icatproject/topcat#326]
I got an error during TopCAT 2.3.0 installation on glassfish.

lindemaria:/tmp/myTest/topcat % ./setup install
JDBC connection pool topcat created successfully.
Attempting to ping during JDBC Connection Pool Creation : topcat - Succeeded.
Command create-jdbc-connection-pool executed successfully.
remote failure: Error occurred during deployment: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: java.util.concurrent.ExecutionException: com.sun.faces.config.ConfigurationException: Unable to parse document 'bundle://198.0:1/com/sun/faces/jsf-ri-runtime.xml': DTD factory class org.apache.xerces.impl.dv.dtd.DTDDVFactoryImpl does not extend from DTDDVFactory.. Please see server.log for more details.

**Comment by andygotz** [comment]
Any news on this issue? Any idea when it will be fixed?

**Comment by jodysalt** [comment]
Hi Andy,

I have attempted to investigate it and was able to replicate it on an Ubuntu machine running Topcat. I undeployed Topcat restarted glassfish, then redeployed Topcat and the error went away and I'm not too sure why.

In the past we've had problems when the underlying Java version gets updated.

Can I suggest you try the procedure outlined above.

Jody

**Comment by ispyb** [comment]
Hi @jodysalt,

I have restarted several times and tested in two different machines (both with Debian). Also I have tried with both Oracle and MySQL.
Which version of Java are you using? Did you try Payara?

I saw in google that someone says that in order to solve the problem a dependency is needed:
https://stackoverflow.com/questions/5833559/maven-org-apache-xerces-impl-dv-dvfactoryexception

A.

**Comment by antolinos** [comment]
Sorry, I left last message when I was logged in Github as ISPyB...

**Comment by jodysalt** [comment]
OK - I've added in that dependecy. Here is the new snapshot:

https://repo.icatproject.org/repo/org/icatproject/topcat/2.3.0-SNAPSHOT/topcat-2.3.0-20170530.131631-3-distro.zip

**Comment by antolinos** [comment]
No luck.

I tried in Payara and Glassfish again with both Oracle and MySQL. 
Which version of JAVA do you use?
Is this deployed in a production (or pre-production) server? 
Do you remember if  you use any annotation that you were not using in version 2.2.*?

Thanks,
A.

**Comment by jodysalt** [comment]
openjdk version “1.8.0_111"

Ok - I’ll go through the whole install process (doing the upgrades one by one).

Jody


On 31 May 2017, at 09:10, antolinos <notifications@github.com<mailto:notifications@github.com>> wrote:


No luck.

I tried in Payara and Glassfish again with both Oracle and MySQL.
Which version of JAVA do you use?
Is this deployed in a production (or pre-production) server?
Do you remember if you use any annotation that you were not using in version 2.2.*?

Thanks,
A.

**Comment by jodysalt** [comment]
What version of Linux are you using?

**Comment by antolinos** [comment]
Both are Debian 8
Linux icat-dataserv 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1
(2016-09-03) x86_64 GNU/Linux
Linux lindemaria 4.8.0-0.bpo.2-amd64 #1 SMP Debian 4.8.11-1~bpo8+1
(2016-12-14) x86_64 GNU/Linux

2017-05-31 11:27 GMT+02:00 Jody Salt <notifications@github.com>:
