### ISSUE TITLE
Topcat can't submit cart with empty datasets and probabley empty investigations

### ISSUE THREAD

**Issue by jodysalt** [icatproject/topcat#327]
Topcat expects a number returned e.g. :

[343423] but instead gets:

[null]

**Comment by fisherab** [comment]
Do you think this is an IDS bug?

Steve

**Comment by jodysalt** [comment]
Actually (thinking more about it) I believe it is an Icat bug. If you run:

select sum(datafile.fileSize) from Datafile datafile, datafile.dataset as dataset where dataset.id = 103100

you get [null] - I would expect [0]. However, if you run:

select count(datafile) from Datafile datafile, datafile.dataset as dataset where dataset.id = 103100

you get [0] as expected. I suspect this could cause problems with the IDS getSize implementation.

(At present Topcat is making use of it's own getSize implementation)
