### ISSUE TITLE
Simplify or customize loading icon

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/topcat#330]
I recently observed a user using TopCAT and noted that they were distracted by the current loading icon (spinner). They didn't think they could do anything until it finished loading, so sat waiting and complained it was slow.

A '-' (a dash) would show that there was no data yet, but not be so distractng to the user or imply the _need_ to wait

- If the loading icon is not cusomisable it should be
- if is it, please can the ISIS one be simplified to a static '-'

**Comment by jodysalt** [comment]
This is something that is configurable. I'll create a solution for Tom Gowland and then add it to Topcat's documentation as configuration recipe.

**Comment by brianritchie1312** [comment]
I don't see anything obvious about this in the documentation, so I don't think this is really "in progress"!
