### ISSUE TITLE
Better error handling if IDS or ICAT go down

### ISSUE THREAD

**Issue by frazzleuk** [icatproject/topcat#346]
Currently if an ICAT or IDS goes down / becomes unavailable. TopCAT just responds with an error message to the user of "TypeError: response is null".

In the topcat.log you can see that it is trying to return a standard glassfish 404 error page which AngularJS fails to handle correctly.

2017-07-10 14:30:23,884 INFO [http-listener-2(4)] HttpClient - send error: GET https://icat-server-url/icat/session/123456789 -> (404) <!DOCTYPE html PUBLIC ...> ...</html>

**Comment by brianritchie1312** [comment]
I've committed a couple of changes (not yet in master) that should improve things, but may not be a complete solution.

The core (and very generic) code that deals with REST requests used a failure handler that assumed that it was being passed a non-null response object, and would always attempt to access response.data. This MAY have been the source of at least some of the "TypeError: response is null" messages; but it could also be coming from somewhere else (for example, if response.data is null, then a rejection with null is passed back).

The other change is a modification to the startup process: if a request for an ICAT's properties fails, topcat will remove that facility from its configuration and attempt to continue; previously, it would simply have stopped. This is similar to the case where a request to IDS for the icat URL fails. It only applies in rare situations where topcat is configured for multiple facilities, but one of them is offline when topcat is started.

These commits are only partial fixes for this issue. I doubt that topcat will react well should an ICAT or IDS stop responding after startup; and my changes only handle special cases during startup.
