### ISSUE TITLE
Shaking My Data area at certain screen sizes

### ISSUE THREAD

**Issue by jsws** [icatproject/topcat#355]
At certain screen sizes Topcat seems to remove and add the right hand side scroll bar very quickly making the whole of the MyData area flicker.

It happens for me using Google Chrome Version 61.0.3163.100 (Official Build) (64-bit) on a 1080p screen at 150% zoom with the window at fullsize.
It doesn't appear to occur on Firefox or IE.

**Comment by brianritchie1312** [comment]
It appears to happen in Chrome for particular zoom sizes and window heights (e.g. for me it happens fullscreen (1920x1080) at 125%; I can also reproduce it at 110% at a smaller height).
I've found a possible fix, by adding overflow-x:scroll to the body in main.css; with this, I can no longer reproduce the flicker. However, it will have to be tested thoroughly as it may introduce problems elsewhere.

In the meantime, a workaround is to change either the zoom level or the window height; even a small change in window height can be enough to stop the flickering.
