### ISSUE TITLE
Improve information in network error messages

### ISSUE THREAD

**Issue by brianritchie1312** [icatproject/topcat#356]
Prompted by Rolf Krahl's experience:

"The symptom is: when I log in as a user, I only get a red error box "No route to host (Host unreachable)" as reply."

It would be useful to have at least the hostname and/or "ICAT/IDS server" in the message.

**Comment by antolinos** [comment]
Hi @brianritchie1312 

For the records, I also got a similar experience with a different error message: EJB transaction rolled back.
Right after that error the user is logged in and can browse his data however it seems that something prevents TopCAT to redirect to the home page when a non-critical error is produced at the server side.

**Comment by brianritchie1312** [comment]
Following the (potential) fix for #346, failure alerts during login should now include the facility name, e.g. "Unable to log into Facility: No route to host" etc.
