### ISSUE TITLE
Do not take any URL arguments in the calls at the topcat REST API

### ISSUE THREAD

**Issue by RKrahl** [icatproject/topcat#357]
TopCAT consist of two parts, the JavaScript part running in the user's browser and a JavaEE application running in GlassFish.  The JavaScript part controls the user interface and the general program flow while large part of the logic and the persistent storage of status information is moved to the JavaEE application.  The communication between the two parts is done via a REST API defined by the JavaEE application that is called from the JavaScript part.

Now, TopCAT also needs to make calls to ICAT and IDS.  The corresponding URLs are configured in `topcat.json`, that is in the configuration of the JavaScript part.  The URLs are passed as arguments to the REST API calls when some method in the JavaEE application needs to call ICAT or IDS.  This way to configure the URLs is problematic:
* Depending on the site specific deployment, a different URL may need to be used to connect to ICAT or IDS when the call is made from the user's browser or from the GlassFish respectively, see the discussion in the mailing list.  The current scheme makes it impossible to distinguish both cases.
* It may also lead to security problems.  The current scheme allows the caller of the JavaEE application's REST API to control to which URL this JavaEE application makes a connection.  It may or may not be an ICAT or IDS service listening at this URL.  Note that anybody may call this API, not just the JavaScript part of TopCAT.  For instance, at least if I understood the sources correctly, the `IdsUploadProxy` listening at `/topcat/user/upload` allows to proxy file uploads with any content to arbitrary URLs at the control of the caller.

I suggest to make the following changes to fix the problem:

* Add facility configuration to `topcat.properties` like this:
  ```
  facility.list = A B C
  facility.A.IcatURL = https://icat.a.example/
  facility.A.IdsURL = https://ids.a.example/
  facility.B.IcatURL = https://icat.b.example/
  facility.B.IdsURL = https://ids.b.example/
  facility.C.IcatURL = https://icat.c.example/
  facility.C.IdsURL = https://ids.c.example/
  ```
  The facilities in `facility.list` should correspond to the names in the entries in `facilities` in `topcat.json`.

* The JavaEE application transforms this configuration to a map on initialization.

* The URL arguments in the calls at the topcat REST API are replaced by facility names.  These names are looked up in the map to get the corresponding URL.

This way, it is possible to clearly distinguish in the configuration between the URLs that are called from the JavaEE application form those that are called from the JavaScript in the user's browser.  And also we retain full control over the URLs that our servers will make connections to.

**Comment by brianritchie1312** [comment]
I thought I had a working implementation of this; but I've spotted a complication. The Javascript configuration in `topcat.json` allows each facility to specify multiple `downloadTransportTypes`, each of which can have a distinct `idsUrl`, e.g.:

```
            "downloadTransportTypes": [
                {
                    "type" : "https",
                    "idsUrl": "https://ids-server.facility.ac.uk"
                },
                {
                    "type" : "globus",
                    "idsUrl": "https://globus-server.facility.ac.uk"
                }
            ],
```

This means that a "simple" map from Facility to IdsUrl in the JavaEE side would not be sufficient. Of course, we could:

- remove the `idsUrl `from `downloadTransportTypes` in `topcat.json` (unless the Javascript is using it elsewhere internally - I've still to check)
- remove the `transportUrl` parameter from the request (but still pass the transport (type))
- add `facility.[facilityName].[transportType].idsUrl = ...` to `topcat.properties` for each combination of facility and transport type. Perhaps the property should be `facility.[facilityName].downloadType.[transportType].idsUrl` to make it clearer that it is download types that are being specified; and perhaps we could drop the final ".idsUrl" (whose name is perhaps misleading). For example:
```
    facility.A.downloadType.https = https://ids.a.example/
    facility.A.downloadType.globus = https://globus.a.example/
    facility.B.downloadType.http = http://ids.b.example/
    facility.B.downloadType.globus = http://globus.b.example/
```

We would still need the `facility.[facilityName].idsUrl properties` as well.

This is adding yet more complexity to topcat.properties; but if we want to avoid passing URLs then I think it is necessary.

**Comment by RKrahl** [comment]
Yes I already suspected some complications of that sort but didn't considered all the details when I wrote the Issue.  I guess the solution that you sketched is - although somewhat cumbersome - still the most simple one that would be possible.  At least, I don't have any better idea for the moment.

**Comment by brianritchie1312** [comment]
We could add a shortcut whereby if a request for downloadType D for facility A is made, but there's no corresponding property `facility.A.downloadType.D`, then `facility.A.idsUrl` would be used. So facilities where all download types use the same IDS url as the "main" one would not need to specify the downloadType properties.

I see that the `transportType idsUrl `is used in the Javascript, so it cannot be removed from `topcat.json`. The uses look somewhat odd to me, but I'm not certain it's worth considering how they might be refactored away.

**Comment by RKrahl** [comment]
The fallback to `facility.A.idsUrl` sounds reasonable.

For the usage of the url in Javascript: I should note that I didn't try any of the download transport types other then https by now.  But as far as I understood what has been discussed in presentations, some of the transport mechanisms seem to act on the client side, starting some helper program that does the download from ids.server via https in the background.  So at least these transport mechanisms would indeed need the url in the JavaScript.
