### ISSUE TITLE
Downloads hang when FullName is empty

### ISSUE THREAD

**Issue by brianritchie1312** [icatproject/topcat#359]
Symptoms: when OK is clicked in the Download Cart dialog, a "busy..." message appears, but nothing happens.

Browser inspection shows that a POST request to topcat/.../cart/{facility}/submit has returned a 400 BadRequestException with 'Index: 0'.

Further investigation reveals that this happens when the ICAT client responds to a query to get the user's fullName with an empty array. The topcat client expects the array to contain at least one string value.

If the empty array response from the ICAT client is correct, then this is a bug.

**Comment by andygotz** [comment]
This could be the same bug we are suffering from. We cannot download more than one file at a time. We look forward to getting a fix of this bug.

**Comment by brianritchie1312** [comment]
Hi Andy,

I doubt that this is the same problem. In the situation I described, NO downloads are possible from the facility in question. I now believe that what’s happening is that the authenticator is allowing me to log in as a user who is unknown to ICAT, so the request for my FullName returns an empty set, which Topcat is (or rather was) not expecting.

Have you submitted an issue for your problem? I don’t see anything that looks relevant, but then I don’t know all the current issues in detail!

Regards,
  Brian
