### ISSUE TITLE
File upload fails when connecting Payara via an Apache reverse proxy

### ISSUE THREAD

**Issue by RKrahl** [icatproject/topcat#372]
I got a problem with file upload with TopCAT 2.3.6.  I consider two different deployment cases:
* In both cases I have all ICAT components (icat.server 4.9.1, authenticators, icat.lucene, ids.server 1.8.0, topcat 2.3.6) deployed in Payara 4.1.2.181 in a Docker container.
* In the first case, I access Payara directly by port forwarding to 8181.
* In the second case, I have an Apache reverse proxy listening on https and proxying calls to all ICAT components using mod_proxy_ajp to Payara on port 8009. Payara is not directly reachable from outside.
* Everything other then file upload using TopCAT works fine in both cases, including file upload to ids.server using a command line client.
* File upload using TopCAT works fine in the first case, but fails in the second case.

The symptom in the second case is the following:
1. In the investigation tab, hit the `Upload` button.
2. The upload dialog opens. Choose a `Dataset name` and drop some files in the `Files` field.
3. Hit `Upload`.
4. The wait icon next to `Upload` spins forever. There is no way out of the upload dialog other the closing the browser tab or entering a new url.

In the ids.log I get:
```
2018-05-02 15:16:49,109 INFO [http-thread-pool::jk-connector(4)] IdsBean - New webservice request: put name='testmsg.txt' datafileFormatId='5' datasetId='9' description='null' doi='null' datafileCreateTime='null' datafileModTime='null'
2018-05-02 15:17:09,235 ERROR [http-thread-pool::jk-connector(4)] IdsBean - I/O exception null putting testmsg.txt to Dataset with id 9
```

The new dataset is created in icat.server.  The file is created in the main storage, but has size zero.  It looks to me as if ids.server gets an error reading the body from the http put request.

I observed the same behavior with the last TopCAT snapshot 2.4.0-20180416.111123-1. With the current snapshot, I don't even get to this point due to #371.

Any idea what I should check?

**Comment by RKrahl** [comment]
It turns out that this issue is still present in the last TopCAT snapshot 2.4.0-20180416.111123-1, my vague hope that this might just go away as a side effect of the solution of #370 did not come true.

My next guess is that this is indeed related to the use of WebSocket connections which seem to be incompatible with an AJP proxy. @brianritchie1312, do you happen to have an overview where WebSocket is used in TopCAT and to which URLs they connect to?

In any case, this seem to be a more fundamental problem. As this is not an issue that has been introduced in the snapshot, but have already been present in the last release, I would agree if you decide not to fix that in 2.4.0, but postpone it to a later release.

**Comment by brianritchie1312** [comment]
When the Upload button is pressed, Topcat constructs a wss (or ws) url "to itself" with arguments facilityName, sessionId, datasetId and datafileFormatId, and the file(s) in the body. The request is handled by an IdsUploadProxy on the Java side, which constructs a PUT request URL based on the facility's idsUrl (on the Java side), from which it creates an HttpUrlConnection, and a DataOutputStream from that. The proxy subsequently responds to message requests by writing and flushing the message to the output stream.
Do you need to modify your proxy to allow wss:// through? Or does something need to change in Topcat? (OK, just seen your latest message - I think this may answer your question, at least in part.)
At least some failures in IdsUploadProxy should be logged in topcat.log; not sure they will help though.

**Comment by RKrahl** [comment]
From what I googled, it seems that WebSocket is indeed incompatible with AJP.  So I would need to change the proxy configuration and maybe use `mod_proxy_wstunnel` in the place of `mod_proxy_ajp`.  (I still didn't understand all the details, implications, and whether this would work at all though,) For this I would need to know the exact URLs (e.g. the local parts) that are used for the WebSocket calls. Is file upload the only place where WebSocket is used?

**Comment by brianritchie1312** [comment]
I don't see it anywhere else, only in the file upload. The url constructed by the Javascript is of the form

`wss://<topcatUrl>/topcat/user/upload?facilityName=...&sessionId=...&datasetId=...&datafileFormatId=...&name=...&contentLength=...`

where topcatUrl is the original value in topcat.json without the leading "https://".  If the original value started with "http://" - or indeed anything else - then the constructed url uses "ws://" instead.

**Comment by RKrahl** [comment]
This did indeed solve the issue. You need to change the proxy configuration to something like the following:
```
	# ProxyPass: first match wins
	ProxyPass /topcat/user/upload ws://icat.internal.example.org:8080/topcat/user/upload
	ProxyPass / ajp://icat.internal.example.org:8009/
```
where `icat.internal.example.org` is the name of the host running Payara. This requires the `mod_proxy_wstunnel` module to be loaded in Apache. Change this to `wss://icat.internal.example.org:8181/topcat/user/upload` topcat is deployed on https (`secure = true`).

It seems that a `ws` proxy can handle ordinary `http` requests as well, so one may simplify the proxy configuration to:
```
	# ProxyPass: first match wins
	ProxyPass /topcat/ ws://icat.internal.example.org:8080/topcat/
	ProxyPass / ajp://icat.internal.example.org:8009/
```
which means that all the requests to topcat will go through the wstunnel rather then through AJP. This has the advantage that the configuration is somewhat more robust against changes in TopCAT. The disadvantage is that (I guess) the `ajp` proxy is more efficient then `http` (and thus `ws`), so one might loose a tiny bit of performance.

In any case, we would need to update the [documentation on Apache proxies](https://icatproject.org/installation/apache-front-end/).

**Comment by RKrahl** [comment]
There may be one thing that you could do on TopCAT's end: if you could dedicate one sub namespace for WebSocket requests.  E.g. you might change the url for the file upload to `wss://<topcatUrl>/topcat/ws/user/upload?[...]` and document that all future WebSocket calls will also be made below the local part `/topcat/ws/`.  That would simplify the proxy configuration.
