### ISSUE TITLE
Use IdsClient.getSize

### ISSUE THREAD

**Issue by brianritchie1312** [icatproject/topcat#378]
This follows Steve Fisher's comment in issue #362.

I am looking at how Topcat uses getSize() at present, considering how it might be changed to use IdsClient's getSize() rather than its own IcatClient.getSize().  However, the signatures are quite different: IdsClient.getSize() takes lists of investigation/dataset/datafile IDs and returns a total size; though one version of IcatClient.getSize() takes similar arguments, it is implemented by summing over the other version, which operates on a single entity.  (This then submits queries directly to ICAT, which we should no longer do.)

Most of Topcat's uses of getSize() are for single entities, but there are a couple of places where the Javascript sums over getSize(entity) requests.

This suggests that we add two getSize() methods to Topcat's IdsClient: one that takes lists of investigation/dataset/datafile IDs and passes them directly to the IDS, and another that takes a single entity and entityType, and uses the first method. (Thus the opposite of what Topcat's IcatClient does at present.)

Those places in the Javascript that use IcatClient.getSize() could then be replaced by almost identical calls to IdsClient.getSize().  The places that construct sums could be rewritten to construct entityID lists instead, and then to pass these to the other IdsClient.getSize().

The other thing to consider is that Topcat uses a cache that maps entities to their sizes; this is maintained by its IcatClient. We need to consider whether this is still useful/necessary; if so, then it will have to be moved to IdsClient, and used by the entity-level version of getSize().

These changes will require thorough testing, particularly load-testing - it is vital that they do not degrade performance for Diamond-sized volumes of data. Indeed, it is hoped that they will make a noticeable improvement.

**Comment by andygotz** [comment]
Hi Brian,

at one point we discussed limiting the dynamic size calculations and instead storing and updating the size only when a dataset is modified. Has this idea been retained / implemented? I remember Steve was against this but his objections did not seem so strong. Maybe this change has already been implemented and you are talking about a different optimisation.

Andy

**Comment by brianritchie1312** [comment]
Hi Andy,

No, this is not what I’m planning at all. Currently, Topcat calculates the size of an entity by submitting a query to the ICAT entity manager that sums the sizes of all the datafiles under that entity. When I made a minor change to the code (see https://github.com/icatproject/topcat/issues/362), Steve commented that it really should be rewritten to use the IdsClient’s getSize operation. I decided to get 2.4.0 out before thinking about it, as I wasn’t sure how much would have to change.

Topcat caches the getSize result for each entity, so it won’t repeat the query so long as the cache is retained.

I am assuming that the IdsClient’s getSize will perform better than the original query. I don’t know how it is implemented. I have a minor concern in that the operation takes lists of investigation/dataset/datafile IDs and returns the total size; but for much of the time, Topcat is “only” interested in the size of a single entity (or rather, the separate sizes of many entities), so the overall performance may not be much different.

Brian

**Comment by RKrahl** [comment]
> I am assuming that the IdsClient’s getSize will perform better than the original query. I don’t know how it is implemented.

It does the following: if there is only one single id in the lists of lists of investigation/dataset/datafile ids, lets say an investigation id, it submits a query like `SELECT SUM(df.fileSize) from Datafile df WHERE df.dataset.investigation.id IN (invid) AND df.location IS NOT NULL`. E.g. it makes only one single search and pushes the summation to the databases backend.
