### ISSUE TITLE
Cart is inherited by a session from a different user

### ISSUE THREAD

**Issue by RKrahl** [icatproject/topcat#384]
Consider the following steps:

1. Log in as User A to TopCAT.
2. Add a few datasets to the cart.
3. Log out.
4. Log in as a different User B, using the same browser.

User B will start in the same tab (My Data, Browse, Search) that User A was shown last before logout. User B will find a cart containing the items selected by User A, even if User B does not have read permission to these items. If User B does not have read permission, several `TypeError: entity is undefined` errors will pop up when showing the cart. The cart will still show some information such as the dataset names and sizes though. In this case, when the user chooses to download the cart nevertheless, the download window will only display `Submitting cart - please wait...` and wait forever.

Apparently, information is leaking from one user's session to the other's. I guess this information (or references to this information) is stored as cookies in the user's browser. I'd suggest that when considering a cookie, TopCAT should always verify that both sessions (the session that the cookies have been set in and the current session) are from the same user and disregard it if this is not the case.

**Comment by brianritchie1312** [comment]
The first part of this issue still remains; indeed, not only is the same tab used, but the browse path will be the same (but will display "Nothing to display" if the new user does not have permission - even the breadcrumb trail is hidden, I think). Resetting the path state would fix this, but would mean that it would be lost when returning as the original user, which may not be desirable. At the moment, Topcat does not remember the old username, so we cannot compare it against the new one and so decide whether or not to reset the path. Adding such a memory may be the simplest solution, but I need to think some more about this.

**Comment by brianritchie1312** [comment]
Strange: I cannot access the pull request that I have made for this branch; I just get a 404. Github won't let me create another pull request, claiming that there is one already. But not one I can use!
