### ISSUE TITLE
Add something like a permalink to an investigation or a dataset

### ISSUE THREAD

**Issue by RKrahl** [icatproject/topcat#393]
Not sure whether something like this already exists, but at least I'm not aware of its existence:

It would be nice to have a  persistent link to an investigation or to a dataset in TopCAT.  This link should open the browse panel with the corresponding investigation or dataset selected.

Obviously, there is a problem: the user needs to be logged in to see the browse panel and the session id is by definition not persistent. But it would be sufficient to have only the part of the link referencing the investigation or the dataset. Then it would be easy to provide a simple web script that logs in as Anonymous, adds the obtained session id as an additional parameter, and replies with a redirect to the full link.

**Comment by brianritchie1312** [comment]
It's possible to bookmark the current browse panel. I just tried this in Firefox: I created a bookmark, then (just to be sure) navigated to a different investigation, then logged out. When I tried to visit the bookmark, topcat showed the login page; but when I logged in, I was taken to the bookmarked browse view, and not the one I was on when I logged out - which is what I hoped would happen.

So users can navigate to an investigation (or presumably a dataset - I haven't tried) and create a bookmark for it.

One downside is that by default Firefox just labels the bookmark as "Topcat", so the user must give it a better name, e.g. "LILS/Proposal 16". The bookmarked URL appears to contain details about the browse state, including the current page, sort options and much else; I haven't looked at it closely. That may be too much to save: if I had carefully set up my sort options and filters, then opened the bookmark only for it to replace them with the "originals", I might not be pleased.

**Comment by RKrahl** [comment]
Thanks for the quick reply. Yes I can confirm that it works as you describe. In fact, the links look rather simple and generic: `https://topcat.example.org/#/browse/facility/<facilityname>/investigation/<investigationid>/dataset` seem to be the link to an investigation and `https://topcat.example.org/#/browse/facility/<facilityname>/investigation/<investigationid>/dataset/<datasetid>/datafile` the link to a dataset. I'm not sure if that in turn depends on the TopCAT configuration (e.g.  “facilities” > [facility] > “hierachy” in topcat.json) though.

**Comment by RKrahl** [comment]
I guess the bookmark label is just the title element from the HTML header. This doesn't bother me. Also I wouldn't care too much about sort options and filters. I guess this will more or less change with every click in TopCAT, so I would consider this highly volatile anyway.

What I was looking for, was a way to link to a particular investigation from outside of TopCAT in a persistent and consistent way. This seem to work fine with these links. The only thing that somewhat bother me here are the ids that appear in the links. They are internal to ICAT and shouldn't be referenced from outside. (I consider TopCAT as part of ICAT with this respect, so it's ok if TopCAT uses them.) For instance they will not survive if you move the ICAT content with export/import to another ICAT instance.

I solved this with a tiny web service script: it takes an investigation name and optionally a dataset name as arguments, looks them up in ICAT, builds up the link cited above, and replies with a HTTP redirection (301) to this link. This works fine and solves the issue for me, so I'll close. (Feel free to mark as invalid, as the missing feature was already there.)
