### ISSUE TITLE
Update angular-ui-grid to 4.0.2

### ISSUE THREAD

**Issue by gc-code** [icatproject/topcat#396]
The version of angular-ui-grid currently being used by Topcat has a frustrating bug where it can scroll very quickly to the bottom of the page without reason. The effect is similar to if you were viewing Topcat on a phone and swiped as quickly as possible. This happens even if the scroll wheel is only moved one position.

I build Topcat with the latest version of angular-ui-grid and couldn't reproduce the bug. There are also reports online that this bug is fixed in the latest version.

To reproduce: Open Topcat on a dataset that has several pages of files. Attempt to scroll with any fine degree of control and you will notice the bug.

**Comment by gc-code** [comment]
Note that this bug is on Chrome browsers only.

**Comment by brianritchie1312** [comment]
I can reproduce this (in Chrome), and confirm that changing angular-ui-grid version to 4.0.2 fixes it. So far, have not found any negative effects. Thanks for finding a solution!
