### ISSUE TITLE
Loading icon does not disappear for empty fields

### ISSUE THREAD

**Issue by gc-code** [icatproject/topcat#410]
In the ISIS production and development Topcat, the GIF indicating that a value is loading (spinning dots) does not disappear when the value does not exist. This behaviour seems to be triggered only when the browser is refreshed when the user is already logged in. The bug has only been found to reproduce reliably on these two Topcat instances.

The best course of action seems to be removing the loading icon for all fields other than size. Size is the only field in Topcat that takes appreciable time to load. Failing that, provide an option in Topcat to disable the loading icon completely.

#330 is a similar issue that has been raised in the past.

**Comment by brianritchie1312** [comment]
If the spinners in blank cells are not going away, this suggests that **some** promise calculation(s) for the page has/have not completed. Unfortunately, if I understand the code correctly the calculation may have nothing to do with the cells. Topcat maintains a global count of outstanding promise requests, and the cell template will show a spinner in blank cells so long as this global count is non-zero.
I've yet to find the "real" culprit in the ISIS systems; there are no (obvious) request failures or dangling requests in the browser console. There may be more information in the topcat or server logs, but finding it may be tricky.

I suspect that Topcat should not be "blindly" showing spinners in all blank cells anyway. I believe that the intention was to show spinners in size / count cells until they had all been calculated, and so it is not correct to show them in cells that will never be non-blank (for example, an Investigation that has no DOI). I will investigate to see whether it is possible to add spinners only to size / count cells; then the spinners will disappear when/if all the size/count calculations complete. Of course, this may mask the real cause.

#330 requested making the spinner configurable; Jody said it was possible, but I don't think he ever did it. The cell template adds a span with style class "loading", so this perhaps could be configured by changing the stylesheet.
