### ISSUE TITLE
Allow external links in table columns

### ISSUE THREAD

**Issue by gc-code** [icatproject/topcat#423]
I would like to be able to make each DOI field into a link that points to the relevant landing page. In the info panel it is possible to specify a link template that the value is inserted into, something similar to that but for a table column would work.

**Comment by brianritchie1312** [comment]
I think this can be done by setting a custom cellTemplate in topcat.json; e.g.:

```
    {
         "field": "study.pid",
         "cellTemplate": "<div class='ui-grid-cell-contents'><a href='http://some.domain.org/{{row.entity.study.pid}}'>{{row.entity.study.pid}}</a></div>"
    },
```

I tried something like that in LILS (using just "name" and "row.entity.name") and it seemed to work. I'm only guessing that it should be "row.entity.study.pid" in your case.

**Comment by gc-code** [comment]
This doesn't seem to work for study.pid. The JSON I am using is as follows:

```
{
    "field": "study.pid",
    "cellTemplate": "<div class='ui-grid-cell-contents'><a href='https://doi.org/{{row.entity.study.pid}}'>{{row.entity.study.pid}}</a></div>"
},
```

I wonder if the fields that can be used in this template are hard coded somewhere.

**Comment by brianritchie1312** [comment]
I think what's happening (or rather not happening) is that Topcat's mechanism for replacing "study.pid" with the full path isn't being applied - it's only a standard AngularJS expression. The more long-winded full path through the entity might work - something like:

```
{{row.entity.studyInvestigations[0].study.pid}}
```

But I am only guessing - I don't have an example to try it on at the moment.

**Comment by gc-code** [comment]
Thank you, specifying the full path as you mentioned above works.
