### ISSUE TITLE
More descriptive names for access/download methods

### ISSUE THREAD

**Issue by kevinphippsstfc** [icatproject/topcat#427]
Currently the Diamond TopCAT has two "Access Method"s when you are at the stage of downloading data. These are https and globus. In the near future we are hoping to add two more options - restoring data to SCARF (the SCD HPC cluster) and restoring data back to the Diamond cluster. If we were to add the two new options to the list, "scarf" and "diamond", then it becomes a bit more confusing as to what all these options are. Probably better would be to have a slightly more descriptive few words eg. "Restore to SCARF" and "Restore to Diamond cluster".

To improve the chances of the user selecting the correct one (and not sending terabytes of data to the wrong place by mistake!) it might also be nice to have a longer description next to the selected option eg. "This restores the selected data to the SCD HPC cluster".

**Comment by brianritchie1312** [comment]
I think this would be straightforward. I propose adding new properties to each downloadType in topcat.json, "displayName" and "description" that (if present) would be used in the downloads form. The current "type" property is used as a key/ID elsewhere and should be a single word. It's not possible (I think) to add tooltips to items in a drop-down choice list, so the description can only be added to the form once a choice is made. Perhaps we could replace the choice list with a radio-button list, but I'm less keen on this.
