### ISSUE TITLE
Duplicates can appear in paginated results

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject/topcat#453]
Duplicates can appear in Topcat results. This creates a discrepancy between the total number of results reported and the number added to the cart when the user seemingly adds 'all' the results to the cart.

## Steps to reproduce:
- In a fresh browser tab, go to a dataset with many files created at the same time, such as [this](https://icat.diamond.ac.uk/#/browse/facility/DLS/proposal/NT11175/investigation/1010754770/dataset/1083896358/datafile) one.
- Open the dev tools panel.
- Filter by Name->Containing: "pasdomain_M8S8_2_"
- Sort by 'Create time' descending (this is the default).
- Scroll down just enough to load an extra 'page' of results.
- Observe the results in the middle of the screen. For me, the files `pasdomain_M8S8_2_1350.cbf` and `pasdomain_M8S8_2_1349.cbf` appear twice.
- Alternatively, in the dev tools panel, look at the IDs of the datafiles returned by the `select distinct datafile ...` queries. Towards the end of the first response and the beginning of the second, there should be duplicate IDs.

## Explanation
Topcat achieves pagination of results by sending multiple queries with `ORDER BY` and `LIMIT` clauses. SQL databases do not guarantee the order of results between queries. Where several results have the same value for the `ORDER BY` clause (eg. the `datafile.datafileCreateTime` in the example above), successive queries could return with these results in different orders. Where these results with a shared value straddle two paginated queries (eg. `LIMIT 0,50`, `LIMIT 50,50`) then the same results could be returned in both queries.

## Solution
Others have experienced this problem. Examples [here](https://stackoverflow.com/questions/2077803/paging-in-sql-with-limit-offset-sometimes-results-in-duplicates-on-different-pag) and [here](https://bugs.mysql.com/bug.php?id=69732). The solution is to guarantee the order of results by appending a `, ID` parameter to all `ORDER BY` clauses to force the database to return results in a strict order over successive paginated queries.

**Comment by brianritchie1312** [comment]
Initial code inspection suggests that there are three places where ORDER BY clauses are constructed. It should be possible to add a final ID to the list in each case. I don't know what would happen if ID were present already - it may not be easy to check.
However, this will be difficult to test. We would need to find a reliable, reproducible failure on a development system, and then show that this change fixes it. It may be difficult to find a failure example in LILS. Though it seems unlikely, we also ought to show that it doesn't break existing correct behaviour!

**Comment by brianritchie1312** [comment]
Alas, one of the three places where `ORDER BY` is constructed is too generic to be useful - we don't have the information available to know which entity's ID should be used. This pushes the problem up to the callers of that piece of code, who now need to add an extra `'entityType.id asc'`. I think this could be done. But should this **always** be done? If no ordering is specified but pagination limits are being applied, is it still possible for duplicates to appear? I suspect so.

**Comment by brianritchie1312** [comment]
I've decided that the answer to my question above is yes, and have modified the code so that the data will always be ordered by ID, if nothing else.
