### ISSUE TITLE
Cart not submitted when IDS is switched off

### ISSUE THREAD

**Issue by dfq16044** [icatproject/topcat#458]
I have been performing some integration testing. 
I have stopped payara on the IDS server. Then I tried through TopCat submit a cart using that IDS, here is what I found:
- by pressing F12 to look at topcat preprod API calls: when TopCat try to send a request to the IDS then the response to the API call is status 400 as expected.
- the cart containing the items is not submitted and under the Downloads tab the following message appears: "A new download has been added".
- the download request does not appear in the admin tab
- I can't see the requested download in the Download window.

Concerning the expected behaviour, it will be better to discuss within the SEG group.
I think that at least it should be appearing in the admin tab to allow the operation team to detect potential issues.

**Comment by brianritchie1312** [comment]
I tested this change by temporarily breaking the submitCart() call (changed it to use a non-existent endpoint) in my development environment. When I click OK in the Download Cart dialog, I get a red message telling me that the download has failed, and the cart has not been emptied. The Download Cart dialog closes, leaving the Cart dialog visible. No "new download added" tooltip appears.

**Comment by dfq16044** [comment]
I tried accessing topcat-dev but I have a blank page with loading ... in the middle.
I tried the following site: https://topcat-dev.esc.rl.ac.uk/
I got the following error after pressing F12 and looking at the console:

Source map error: request failed with status 404
Resource URL: https://topcat-dev.esc.rl.ac.uk/scripts/vendor.600d584f.js
Source Map URL: angular-inform.js.map
