### ISSUE TITLE
Manage items in a cart

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#83]
## User Storey

As a user, I want to be able to view and manage the cart, so I can see what items where added to the cart, the size of each item and the ability to remove items I have added by mistake.

## Acceptance Criteria

  - User must be able to see the size of an item in the cart
  - User must be able to identity which facility the file is from
  - User must be able to see the availability of the items
  - User must be able to remove an unwanted item fro the cart
  - User must be able to see the total item size in the cart

[Mockup link - cart](https://stfc.mybalsamiq.com/projects/topcatv2-stfc/Main%20Storage%20Only%20Download%2001%20-%20Cart)

**Comment by jodysalt** [comment]
To complete - needs to identify facility and see total item size.
