### ISSUE TITLE
Option to exclude items that contains no data from being displayed

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#87]
## User Storey

As a user, I want the option to exclude items that contain no data from being displayed. For example, if an instruement contains no investigation, I should no see the instrument in the instrument list.

## Acceptance Criteria

  - Site administrator must be able to enable/disable this option

**Comment by kevinphippsstfc** [comment]
Important for Diamond

**Comment by kevinphippsstfc** [comment]
Admin option or user toggle? - ask Diamond

**Comment by tomgriffinstfc** [comment]
Default filters

**Comment by jodysalt** [comment]
This is currently not possible by a filter as the size returned by a separate getSize rest request, so can't be filtered via jpql (in a way that would be quick). However, would this still be an issue if #88 was implemented (i.e. exclude items in the future)? Or if #88 was implemented, would this still be high priority?

**Comment by tomgriffinstfc** [comment]
Implemented for future visits, which meets Diamond's basic requirement
