### ISSUE TITLE
Option to exclude items that are in the future

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#88]
## User Storey

As a user, I want the option to exclude items that have a start date set in the future.

## Acceptance Criteria

  - Site administrator must be able to enable/disable this option

**Comment by kevinphippsstfc** [comment]
Important for Diamond

**Comment by kevinphippsstfc** [comment]
Admin option or user toggle? - ask Diamond

**Comment by tomgriffinstfc** [comment]
Default filter options
